---
title: "1. Instalción de R y herramientas auxiliares"
output: html_notebook
---

## 1.1 Instalación de R

El primer paso para trabajar en R es ... instalarlo. Para ello, visitad el siguiente enlace web y descargar la última versión de R (en caso de usar Windows):

https://cran.r-project.org/bin/windows/base/

## 1.2 Instalación de R Studio

## 1.3 Recursos on-line

Aunque el objetivo de este curso es proporcionar las herramientas necesarias para poder utilizar R y realizar modelos, sería imposible incluir con detalle todas las particularidades de R o todas las incidencias/dudas que pueden surgir mientras se realizan modelos. Por ello, se presentan a continuación recursos on-line vitales para solucionar estas incidencias y seguir aprendiendo: 

### 1.3.1 Kaggle

### 1.3.2 StackOverflow

StackOverflow es un Q&A de programación en la que los usuarios crean post con dudas (y otros resuelven dichas dudas) en mucho lenguajes de programación, incluido R. Por ejemplo, a continuación se muestra un hilo de StackOverflow con dudas sobre como contar el número de missings en un DataFrame en R:

https://stackoverflow.com/questions/26266362/how-to-count-the-nan-values-in-a-column-in-pandas-dataframe

En general, la mayoría de dudas que puedan surgir están ya resueltas en StackOverflow, solamente hace falta buscar con un poco de paciencia. Sin embargo, también podeis abrir una cuenta (es gratis!!) y postear vuestras propias dudas.